#!/bin/bash
source acp.sh


FILE_PATH=$1
OUT_DIR=$2

if [ -z "$OUT_DIR" ]; then
  OUT_DIR='./'
fi

if [ -d "$FILE_PATH" ]; then
  echo "FATAL: Is a directory: $FILE_PATH"
  exit 1
fi

if [ ! -f "$FILE_PATH" ]; then
  echo "FATAL: Not found: $FILE_PATH"
  exit 1
fi

FILE_ABS_PATH=`realpath "$FILE_PATH"`
FILE_NAME=`basename "$FILE_ABS_PATH"`
FILE_SIZE=`stat --printf="%s" "$FILE_PATH"`

sendAcpData "getFile" "$FILE_ABS_PATH" "$OUT_DIR" "$FILE_NAME" "$FILE_SIZE"
