#!/bin/bash
source acp.sh


FILE_PATH=$1
OUT_DIR=$2

if [ -z "$OUT_DIR" ]; then
  OUT_DIR='./'
fi

if [ ! -d "$OUT_DIR" ]; then
  echo "FATAL: Is not a directory: $OUT_DIR"
  exit 1
fi

if [ -z "$FILE_PATH" ]; then
  echo "FATAL: FILE_PATH is empty"
  exit 1
fi

OUTDIR_ABS_PATH=`realpath "$OUT_DIR"`

sendAcpData "putFile" "$FILE_PATH" "$OUTDIR_ABS_PATH"
